package com.coen241.schedulerservice.model;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;
import com.coen241.schedulerservice.common.Status;
import lombok.Data;

import java.util.List;
import java.util.Map;

@Data
@DynamoDBTable(tableName = "Workflow")
public class Workflow {

    @DynamoDBHashKey(attributeName = "id")
    @DynamoDBAutoGeneratedKey
    private String workflowId;
    @DynamoDBAttribute(attributeName = "specId")
    private String workflowSpecId;
    @DynamoDBAttribute(attributeName = "status")
    private Status workflowStatus;
    @DynamoDBAttribute(attributeName = "taskList")
    private List<Task> taskList;
    @DynamoDBAttribute
    private Map<String, String> attributes;
}
