package com.coen241.schedulerservice.model;

import com.amazonaws.services.dynamodbv2.datamodeling.*;
import com.coen241.schedulerservice.common.Status;
import lombok.*;

import java.time.Instant;
import java.util.List;
import java.util.Map;

@Data
@NoArgsConstructor
@AllArgsConstructor
@DynamoDBTable(tableName = "workflow")
public class Workflow {

    @DynamoDBHashKey(attributeName = "id")
    @DynamoDBAutoGeneratedKey
    private String workflowId;
    @DynamoDBAttribute
    private String workflowSpecId;
    @DynamoDBAttribute
    private String name;
    @DynamoDBTypeConvertedEnum
    @DynamoDBAttribute(attributeName = "status")
    private Status workflowStatus;
    @DynamoDBAttribute(attributeName = "taskList")
    private List<TaskInstance> taskInstanceList;
    @DynamoDBAttribute
    private Map<String, String> attributes;
    @DynamoDBAttribute
    private String createdAt;
    @DynamoDBAttribute
    private String updatedAt;
}
